version: "3.8"

networks:
  db_network:
    driver: bridge

services:
  redis:
    image: redis
    ports:
      - "7002:6379"
    networks:
      - db_network
    restart: always

  web:
    build:
      dockerfile: Dockerfile_mac
    command:
      - /bin/bash
      - -c
      - |
        cd ebpf_sse && python3 bashreadline.py &
        uvicorn ebpf_sse.api:app --host 0.0.0.0 --port 8001 --workers 5 --log-level info
    ports:
      - "7778:8001"
    volumes:
      - .:/workspace
      - /lib/modules:/lib/modules:ro
      - /etc/localtime:/etc/localtime:ro
    privileged: true
    pid: "host"
    networks:
      - db_network
    depends_on:
      - redis
    restart: always
    tty: true
    stdin_open: true
