#https://github.com/singe/ebpf-docker-for-mac
FROM docker/for-desktop-kernel:5.15.49-13422a825f833d125942948cf8a8688cef721ead AS ksrc

FROM ubuntu:latest

WORKDIR /
COPY --from=ksrc /kernel-dev.tar /
RUN tar xf kernel-dev.tar && rm kernel-dev.tar

RUN apt update
RUN apt install -y kmod python3-bpfcc python3-pip

RUN mkdir /workspace/
WORKDIR /workspace/
ADD . /workspace/
RUN python3 -m pip install -r requirements.txt
CMD mount -t debugfs debugfs /sys/kernel/debug && /bin/bash
